<a href="https://colab.research.google.com/github/mkjubran/IntroToPython-NonIT/blob/main/ENCS313_Python_Experiment_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Experiment 10: Learning & Programming Python


Example #1


In [3]:
import numpy as np 
a = np.array([1, 2, 3]) 
print(type(a)) 
print(a.shape) 
print(a[0], a[1], a[2]) 
a[0] = 5
print(a)
b = np.array([[1,2,3],[4,5,6]]) 
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


Example #2

In [4]:
a = np.zeros((2,2)) 
print(a)
b = np.ones((1,2))
print(b)
c = np.full((2,2), 7,dtype="int64")
print(c)
d = np.eye(2) 
print(d)
e=np.random.random((2,2))
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.25181312 0.09736926]
 [0.48720531 0.65236808]]


Example #3

In [6]:
import numpy as np
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]]) 
b = a[:2, 1:3]
print(a[0, 1])
b[0, 0] = 77
print(a[0, 1])

2
77


Example #4

In [9]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
row_r1 = a[1, :]
row_r2 = a[1:3, :]
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[5 6 7 8] (4,)
[[ 5  6  7  8]
 [ 9 10 11 12]] (2, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


Example #5

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a[[0, 1, 2], [0, 1, 0]]) # Prints "[1 4 5]" 
print(np.array([a[0, 0], a[1, 1], a[2, 0]])) # Prints "[1 4 5]" 
print(a[[0, 0], [1, 1]]) # Prints "[2 2]" 
print(np.array([a[0, 1], a[0, 1]]))

Example #6

In [10]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)
b = np.array([0, 2, 0, 1])
print(a[np.arange(4), b]) # Prints "[ 1 6 7 11]" a[np.arange(4), b] += 10
print(a) # prints "array([[11, 2, 3],

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Example #7

In [11]:
a = np.array([[1,2], [3, 4], [5, 6]])
bool_idx = (a > 2)
print(bool_idx) # Prints "[[False False] # [ True True]
print(a[a > 2]) # Prints "[3 4 5 6]"
print(a[bool_idx]) #Prints"[3456]"

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


Example #8

In [ ]:

x = np.array([1, 2]) 
print (x.dtype)
x = np.array([1.0, 2.0]) 
print (x.dtype)
x = np.array([1, 2], dtype=np.int64) # Force a particular datatype 
print (x.dtype) # Prints "int64"

Example #9

In [ ]:

x = np.array([[1,2],[3,4]], dtype=np.float64) 
y = np.array([[5,6],[7,8]], dtype=np.float64)

print(x + y)
print(np.add(x, y))

print(x - y)
print(np.subtract(x, y))

print(x * y)
print(np.multiply(x, y))

print(x / y)
print(np.divide(x, y))

print(np.sqrt(x))

Example #10

In [ ]:
x = np.array([[1,2],[3,4]]) 
y = np.array([[5,6],[7,8]]) 
v = np.array([9,10])
w = np.array([11, 12]) 
print(v.dot(w)) 
print(np.dot(v, w)) 
print(x.dot(v)) 
print(np.dot(x, v)) 
print(x.dot(y)) 
print(np.dot(x, y))

Example #11

In [ ]:
#Write your code here


Example #12

In [ ]:
#Write your code 


Example #13

In [ ]:
#Write your code here


Example #14

In [ ]:
#Write your code here


Example #15

In [ ]:
#Write your code here


Example #16

In [ ]:
#Write your code here


Example #17

In [ ]:
#Write your code here


Example #18

In [ ]:
#Write your code here


Example #19

In [ ]:
#Write your code here


Example #20